" Basics {{{
if (!isdirectory(expand('$HOME/.vim/repos/github.com/Shougo/dein.vim')))
  call system(expand('mkdir -p $HOME/.vim/repos/github.com'))
  call system(expand('git clone https://github.com/Shougo/dein.vim $HOME/.vim/repos/github.com/Shougo/dein.vim'))
endif


set nocompatible

  set runtimepath+=~/.vim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.vim'))
call dein#add('Shougo/dein.vim')
call dein#add('haya14busa/dein-command.vim')
call dein#add('sickill/vim-monokai')
call dein#add('airblade/vim-gitgutter')
call dein#add('martinda/Jenkinsfile-vim-syntax')
call dein#add('leafgarland/typescript-vim')
if dein#check_install()
  call dein#install()
endif
call dein#end()

" }}}

" Colours {{{
" Enable syntax highlighting
syntax on

colorscheme monokai
" }}}

" Editing {{{
" Allow buffer switching without saving
set hidden

" Backspace works like you expect it
set backspace=indent,eol,start
" }}}

" Spaces & Tabs {{{
" When no filetype-specific is enabled, opening a line keeps the same indent level
set autoindent

" Tabs are converted to spaces
set expandtab

" How many columns Vim uses for displaying a <Tab>
set tabstop=2

" How many columns Vim uses when <Tab> is pressed in Insert Mode
set softtabstop=2

" How many columns text is indented with reindent operations
set shiftwidth=2

set smartindent
" }}}

" Layout {{{
" Display line numbers
set number

" Highlight matching parenthesis
set showmatch

" Show where the cursor is
set ruler

" Highlight the current line
set cursorline

" Always display the status line
set laststatus=2

" Use visual bell instead of beeping when doing something wrong
set visualbell

" Reset the terminal code for the visual bell
set t_vb=

" Set the command window height to 2 lines
set cmdheight=2

" Show command being typed
set showcmd

" Better command-line completion
set wildmenu
" }}}

" Mappings {{{
" Turn off search highlighting until the next search
nnoremap <Leader>l :nohls<CR>
" }}}

" Searches {{{
" Highlight searches
set hlsearch

" Search as characters are entered
set incsearch

" Use case insensitive search
set ignorecase

" If the search pattern contains uppercase characters, use case sensitive search
set smartcase
" }}}

" Powerline {{{
" Config python
let g:powerline_pycmd="py3"

" Always display status bar
set laststatus=2
" }}}

" Splits {{{
" Easier split navigation mappings
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

" More natural split opening
set splitbelow
set splitright
" }}}

