# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# IBM CPLEX 64bit
CPLEX="/opt/ibm/ILOG/CPLEX_Studio_Community1262/cplex/bin/x86-64_linux"

if [ -d $CPLEX ] ; then
	PATH="$CPLEX:$PATH"
fi

# Arduino IDE
ARDUINO="$HOME/bin/arduino-nightly"

if [ -d $ARDUINO ] ; then 
	PATH="$ARDUINO:$PATH"
fi

# Personal scripts
BASH_SCRIPTS="$HOME/Developer/Bash"

if [ -d $BASH_SCRIPTS ] ; then
	PATH="$PATH:$BASH_SCRIPTS"
fi

# Visual paradigm
VISUALPARADIGM="$HOME/bin/VisualParadigm"

if [ -d $VISUALPARADIGM ] ; then
	PATH="$VISUALPARADIGM:$PATH"
fi


