if [ ! -e ~/.bash_functions ] ; then
	echo "~/.bash_functions missing."
	return 1
else
	. ~/.bash_functions
fi

# ls shortcuts
LS_OPTIONS="-1FGhp"

UNAME=`uname`
if [ "$UNAME" = "Darwin" ] ; then
	# OS X
	LS_OPTIONS="$LS_OPTIONS -G"
else
	# Linux
	LS_OPTIONS="$LS_OPTIONS --color=auto"
fi
unset UNAME
alias ls="ls $LS_OPTIONS"
alias ll="ls $LS_OPTIONS -l"
alias la="ls $LS_OPTIONS -A"
alias lla="ls $LS_OPTIONS -lA"

unset LS_OPTIONS

# As seen on http://natelandau.com/my-mac-osx-bash_profile/
alias cp="cp -iv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"

# Some commands shortcut for pdfs and images
set_cmd_var openpdf evince
set_cmd_var openimg ristretto

# Folder shortcuts
MODELICA="$HOME/Developer/Modelica/progetto-OS2"
set_dir_var MODELICA

# LaTeX
LATEX="$HOME/Developer/LaTeX"
if set_dir_var LATEX ; then
	ALGEBRA="$LATEX/uni/II-anno/I-semestre/algebra"
	set_dir_var ALGEBRA
	INTEGRALE="$LATEX/uni/I-anno/II-semestre/calcolo-integrale"
	set_dir_var INTEGRALE
	ANALISI="$LATEX/uni/III-anno/I-semestre/analisi-2"
	set_dir_var ANALISI
	COMBINATORIA="$LATEX/uni/III-anno/I-semestre/combinatoria"
	set_dir_var COMBINATORIA
	AUTOMI="$LATEX/uni/III-anno/I-semestre/automi"
	set_dir_var AUTOMI
fi

# SoftEng
SOFTENG="$HOME/Documents/SoftEng"
set_dir_var SOFTENG

